// adding a test comment ..

#pragma config(StandardModel, "RVW Fantastilaunch")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int defaultPause = 50;
void pause(int secs)
{
  motor[leftDrive] = 0;
  motor[rightDrive] = 0;
  motor[clawArm] = 0;
  motor[clawExtender] = 0;
  motor[clawMotor] = 0;
  motor[clawWrist] = 0;
  wait1Msec(secs);
}
void moveBackward(int secs)
{
	 motor[leftDrive] = -127;
   motor[rightDrive] = -127;
   wait1Msec(secs);
}
void moveFoward1(int secs)
{
   motor[leftDrive] = 127;
   motor[rightDrive] = 127;
   wait1Msec(secs);
}
void turnLeft1(int secs)
{
 motor[rightDrive] = 90;
 motor[leftDrive] = -90;
  wait1Msec(secs);
}
void turnRight1(int secs)
{
 motor[rightDrive] = -60;
 motor[leftDrive] = 60;
  wait1Msec(secs);
//  pause(1);
}
void clawDown(int secs)
{
	motor[clawWrist] = -60
}
// sharan & Aryan - clawWrist > moveForward > clawMotor > clawArm
void pickUpCap()
{
// motor[clawArm] = 63;
// wait1Msec(20);
motor[clawExtender] = 127
wait1Msec(300);
motor[clawWrist]= -127;
 wait1Msec(800);
 pause(500);
 motor[clawMotor] = 127;
 wait1Msec(500);
  motor[clawArm] = 127;
 wait1Msec(1400);
 pause(500);
 turnRight1(250);
 pause(500);
 //moveBackward(150);
motor[clawArm] = 60;
wait1Msec(200);
pause(500);
 motor[clawMotor] = -127;
 wait1Msec(500);
 // put a pause to clawExtender
// pause(defaultPause);
// motor[clawArm] = -63;
// wait1Msec(30);
 // wait1Msec(1);
 // motor[clawArm] = -63;
}
task main()
{
  moveFoward1(1200);
  pause(500);
  pickUpCap();
//  turnRight1(100);

}
