#pragma config(StandardModel, "RVW Fantastilaunch")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forward(int time)
{
	motor[RightDrive] = 127;
	motor[LeftDrive]  = 127;
	wait1msec(time);
}
void turnRight(int time)
{
	motor(RightDrive) = -127;
	motor(LeftDrive) = 127;
	wait1msec(time);
}
void turnLeft(int time)
{
	motor(RightDrive) = 127;
	motor(LeftDrive) = -127;
	wait1msec(time);
}
void pause(int time)
{
	motor(RightDrive) = 0;
	motor(LeftDrive) = 0;
	wait1msec(time);
}
void shoot()
{
	motor(clawArm) = 127;
	wait1msec(500);
	pause(1000);
	motor(launchArm) = 64;
	wait1msec(150);
	pause(500);
	motor(LeftIntake) = -127;
	motor(RightIntake) = -127;
	wait1msec(1000);
}
void firstflag()
{
	motor(clawArm) = -127;
	wait1msec(500);
	motor(launchArm) = -64
	wait1msec(75);
	forward(1000);

}
task main()
{
	turnLeft(300);
	forward(1300);
	turnleft(250);
	forward(150);
	pause(1000);
	shoot();
	firstflag();

}
